### ISSUE TITLE
Strange error with `gist edit`

### ISSUE THREAD

**Issue by fiatjaf** [jdowner/gist#13]
```
fiatjaf@spooner:~$ gist edit d2d6cebb4da2d425e8b5
Cloning into 'd2d6cebb4da2d425e8b5'...
Warning: Permanently added the RSA host key for IP address '192.30.252.142' to the list of known hosts.
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (3/3), done.
Checking connectivity... done.
sh: 1: traceroute fiatjaf.cloudant.com: not found
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
```

The bizarre `traceroute fiatjaf.cloudant.com` the shows up there is in the contents of the gist itself: https://gist.github.com/fiatjaf/d2d6cebb4da2d425e8b5

**Comment by jdowner** [comment]
What is your EDITOR environment variable set to?

**Comment by jdowner** [comment]
I tried deleting my EDITOR variable and reproduced the same error. I have an issue to detect this situation and handle it better. I just thought I would have more time to get to it before someone found it ;)

**Comment by fiatjaf** [comment]
It is working pretty well after https://github.com/jdowner/gist/commit/9ec44aa2c978617c81ff7775532fce830c1afd16. Thank you very much.
