### ISSUE TITLE
Problem with get content when "utf-8 content"

### ISSUE THREAD

**Issue by Yurij-** [jdowner/gist#19]
it should be nice to have unicode 
$ gist content d2409da1f2ad59f4a76c

'ascii' codec can't encode characters in position 4-8: ordinal not in range(128) 
therefore  if i try get content of "pure ASCII  " file it nicely printed to stdout. 
i use python 2.7.6. on ubuntu
 thanks for yours efforts

**Comment by jdowner** [comment]
Thanks for adding this issue, @Yurij-. I have a basic solution for the problem but as with any unicode problem there are always edge cases that need to be account for. In particular, I need to make sure that a solution works for both python2 and python3, and that if a user does not have a terminal that supports unicode that the resulting output is reasonable (i.e. does not result in an error). I'm hoping to have something in place soon though.

**Comment by jdowner** [comment]
I have push a fix for this. Apologies for taking so long. Let me know if you have any more problems with it.
