### ISSUE TITLE
Cleanup config handling

### ISSUE THREAD

**Issue by jdowner** [jdowner/gist#24]
This issue has two parts. The first relates to the amount of a code in bin/gist that is devoted to managing the config, particularly in the main function. Ideally, the main function should read as a list of the actions that can be performed. Although the config-related code clearly needs to run, it is a different level of abstraction and should not obscured the actions, which are the intent of the main function.

Secondly, ConfigParser is a little painful to use and it might help to create a thin wrapper around it. It would be nice if (1) it could be treated more like a dict (since there is only one section of interest), and (2) it should provide sensible defaults for variables where it makes sense.

**Comment by rtfmoz2** [comment]
parser = configparser.ConfigParser()
parser.read_file(filename)
confdict = {section: dict(parser.items(section)) for section in parser.sections()}

is that useful to you?

**Comment by jdowner** [comment]
> parser = configparser.ConfigParser()
> parser.read_file(filename)
> confdict = {section: dict(parser.items(section)) for section in parser.sections()}
> 
> is that useful to you?

Roughly speaking, the work for this ticket relates to create a config module and encapsulating all of the config-related functionality that is currently in `client.py`. The `config` object itself isn't really a problem, it is more that the amount of config code has grown to the point where it should be properly refactored and put into it's own module.
