### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by ramnes** [jdowner/gist#36]
Hi there,

I can't manage to make `gist` work under a proxy, even by giving all the proper proxy settings through environment variables.

```
$ proxy gist create "" my-file
1471632135.883 ERROR[gist] HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /gists?access_token=****** (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9eb951d198>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

`proxy` being an alias for `http_proxy="http://my-proxy:8080/" https_proxy="http://my-proxy:8080/" HTTP_PROXY=$http_proxy HTTPS_PROXY=$https_proxy`.

**Comment by jdowner** [comment]
Salut ramnes,

I would like to get this to work with gist, but it is not a mechanism I have worked with before. Typically I use ssh to create a socks proxy for my browser but that is all. It seems that the above environment variables are a convention use by a lot of command line tools, but it is not backed by any shared mechanism. The "requests" library that I am using is supposed to support the upper case version, and I think it is doing that correctly but I have reproduced the "max retries" message while experimenting with it. But I have also got it to work at times...

Just a couple of notes though. One of the warnings on the my-proxy website states that they do not control the proxies and that service may be sproadic. Is it possible that that is the problem? Also, the proxy URLs are not treated the same by all command line tools, e.g. if you do not specify the port explicitly in curl it assumes you are intending to use port 1080, while other tools assume port 80. I know that you have added the port in you example above, but just in case that is placeholder you have added for your example, I thought I would mention it.

Really, I just wanted to let you know that I am working on this, but I have not come to a conclusion yet. However, let me ask you for your input on something. There is an additional option of adding the proxies explicitly to the gist config file. While I would still want gist to use the mechanism that other tools are using, would you find any value in a gist-specific option?

**Comment by jdowner** [comment]
One useful tool is strace,
```
strace -e trace=connect python
```
what I am seeing is that requests is using the proxy when I invoke it directly but gist is not. I suspect this could be related to the way that I am manually creating the Request object.

**Comment by jdowner** [comment]
I have pushed a fix for the issue. Thanks for letting me know about it and let me know if you have any more problems.

**Comment by ramnes** [comment]
Hey @jdowner,

Sorry I didn't answer sooner. Your fix works! Thanks a bunch.

Although, when I use a wrong token, when I try to upload an empty file or when I do `echo "" | proxy gist create ""`, I have a non-descriptive error: `1471800999.005 ERROR[gist] 'html_url'`.

I can't tell if that issue was present before or not. Do you want me to open another issue about this or do you think it's related to your implementation here?

**Comment by jdowner** [comment]
I don't think that is a new error and is covered by an existing issue (https://github.com/jdowner/gist/issues/8)

**Comment by ramnes** [comment]
Woops, I searched for "html_url" in the issue filter and nothing came back, sorry.
