### ISSUE TITLE
Compatibility with windows

### ISSUE THREAD

**Issue by FluxDZ** [jdowner/gist#37]
In the send function of gist, there is a change you can make to make the request compatible with windows.

On line 168 of gist.py change it to : 

    `request.url = '/'.join([request.url, stem])`

This works as the original

    tries to join the os path but in windows the paths are \ instead of /

**Comment by jdowner** [comment]
I have implemented a fix that hopefully will work for you. However, I have no access to testing on a windows machine so please let me know if there are still problems.
