### ISSUE TITLE
Support running a command to get API token from config file

### ISSUE THREAD

**Issue by kbenzie** [jdowner/gist#65]
Would there be interest in supporting a command syntax in the config file to enable the collection of the GitHub API token from an encrypted source?

Git options support running commands in config options with a `!` prefix. My proposal is to support a similar syntax in this tool:

```
[gist]
token: !gpg --decrypt github-token.gpg
```

I will happily contribution this change.

**Comment by jdowner** [comment]
I think that's a terrific idea! Please feel free to put a PR up when you have something implemented.

**Comment by kbenzie** [comment]
Great. I'll do that as soon as I can.
