### ISSUE TITLE
Use Authorization HTTP header, since access_token is deprecated

### ISSUE THREAD

**Issue by nealmcb** [jdowner/gist#79]
Thanks for this tool - worked like a charm.  But Github just emailed me:
> ... your personal access token using python-requests/1.2.0 was used as part of a query parameter to access an endpoint through the GitHub API:  https://api.github.com/gists

> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.
> Depending on your API usage, we'll be sending you this email reminder on a monthly basis for each token and User-Agent used in API calls made on your behalf.                                                                                                                                        
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

> Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

That page currently says that brownouts of the feature are scheduled to begin September 30, 2020, and it will stop working on November 13.

**Comment by veo-jdowner** [comment]
Thanks for bringing this to my attention (and providing useful info)! I'll get onto this quickly so you don't get spammed each month :)

**Comment by jdowner** [comment]
Fortunately, it is small change. I will get into into pypi shortly.

**Comment by jdowner** [comment]
Done. [v0.9.2](https://pypi.org/project/python-gist/0.9.2/) should fixes this issue.

**Comment by nealmcb** [comment]
Amazingly fast work - thank you!!
