### ISSUE TITLE
List required arguments after options

### ISSUE THREAD

**Issue by nealmcb** [jdowner/gist#82]
I finally figured out why `gist /tmp/my_pastebin_file` kept dumping me into the editor rather than simply uploading the file I was specifying.
I skimmed the documentation:

    gist create <desc> [--public] [--encrypt] [FILES ...]

 too quickly and didn't look before the `[--encrypt]` option, assuming that the only positional arguments were the optional FILES.

I think it would be more conventional to list the positional arguments at the end of the Usage summaries, after all the options, for the `create` and `content` commands.

Thanks again!

**Comment by rtfmoz2** [comment]
Can you provide an example?

**Comment by nealmcb** [comment]
Sorry, I guess I meant `gist create`:

```
$ gist create /tmp/my_pastebin_file
Waiting for Emacs...
```

**Comment by nealmcb** [comment]
So the usage might be clearer to me as:
`gist create [--public] [--encrypt] <desc> [FILES ...]`

**Comment by jdowner** [comment]
I think this is something that could be easily supported if `gist` was using `argparse`. However it is currently using `docopt` which affords less flexibility in parsing the arguments. I have created a ticket to switch from `docopt` to `argparse`, which is something I would like to do anyway (see https://github.com/jdowner/gist/issues/89). Hopefully that change will resolve this issue as well.

@nealmcb One thing I do want to mention is that the original interface must continue to work. I'm happy if it can be flexible enough to support `<desc>` after the options, but I do not want to break the interface for other users.

**Comment by jdowner** [comment]
@nealmcb I've completed the transition from doctop to argparse. I think it provides the flexibility you're asking for. Can I ask you to download the latest version from [master](https://github.com/jdowner/gist/tree/master) to make sure it works? If it does, I'll close this issue and push a new version to pypi.

**Comment by nealmcb** [comment]
Thanks again.  I installed the latest (which is still labeled with version 0.9.2) and it works with the more natural syntax I like:

    gist create --public "test gist command" README.rst 

but not with this usage, as still documented in the README:

    gist create "test gist command desc first" --public README.rst

**Comment by jdowner** [comment]
@nealmcb Sorry to leave you hanging on this. I tried several different approaches to support this additional syntax but it became quite convoluted and brittle. So I have decided that I am not going to make this change and keep the current syntax.
