### ISSUE TITLE
Should not advise users to install with `sudo`

### ISSUE THREAD

**Issue by alichtman** [jdowner/gist#83]
The README states to install this program with `sudo pip install ...`. This introduces needless security risks. `pip install` works just fine.

**Comment by nealmcb** [comment]
Why was this closed? Running the arbitrary Python code in setup.py as root:

 * is very insecure
 * risks messing up the OS packaging system
 * is outdated, especially now that modern pip defaults to `--user` mode.

See e.g. [Is \`sudo pip install\` still a broken practice? \- Ask Ubuntu](https://askubuntu.com/questions/802544/is-sudo-pip-install-still-a-broken-practice)

I agree with OP that the README should be fixed.
