### ISSUE TITLE
Handle case where user does not have EDITOR defined

### ISSUE THREAD

**Issue by jdowner** [jdowner/gist#9]

**Comment by fiatjaf** [comment]
I don't have an `EDITOR` variable and never had. I use Ubuntu. But the "editor" command works fine for me.

```python
subprocess.Popen(['editor', file])
```

will work here and open `vim`, but I don't know if it is compatible with other distros/OSes.

**Comment by jdowner** [comment]
If you are using bash, it is common to have EDITOR or VISUAL set in your .bashrc file so that programs that need to open an editor know which one to use. This is true for all distros AFAIK.

**Comment by fiatjaf** [comment]
I use fish, but I have set `vim` as my default text editor manually somewhere. It is not a fish-specific thing. `editor` runs fine both in bash and fish.

**Comment by jdowner** [comment]
Ah, I think this might be part of the debian 'alternatives' system. I will make sure that I incorporate this.

**Comment by jdowner** [comment]
I have push a fix to (hopefully) handle this problem.
