### ISSUE TITLE
gist edit fails with ERROR[gist] handle_gist_edit() takes 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by nealmcb** [jdowner/gist#95]
```
$ gist edit xyzzy
1615939555.966 ERROR[gist] handle_gist_edit() takes 2 positional arguments but 4 were given

$ gist version
v0.9.2
```

Yeah, I know xyzzy isn't a valid gist, but the same thing happens with a valid gist id....

**Comment by jdowner** [comment]
@nealmcb it looks like you were running from the tip of master rather than the actual v0.9.2 version. I have pushed a bunch of fixes and bumped the version to 0.10.0, which should address this issue.

**Comment by nealmcb** [comment]
Good point. More precisely, I'm running this version:

158059c 2020-11-15 E (HEAD -> master, origin/master) Merge pull request #93 from jdowner/staging [GitHub]

not the one tagged 0.9.2:

cd53b97 2020-04-02 E (tag: v0.9.2) Merge pull request #81 from jdowner/staging [GitHub]

I wonder how hard it would be to add the commit info to the version command output.

I actually had some run-arounds even figuring out which "gist" project I was using since the repo name is a common one (e.g. there's a [Ruby-based `gist`](https://github.com/defunkt/gist) out there also). Pointing to the canonical source or documentation page from the output of `--help` might be a good idea also.

Thanks again for this great software!

**Comment by nealmcb** [comment]
Hmm - but I just installed v0.10.0 (via `git pull` and `pip install .`) and get the same error:

```
$ gist version
v0.10.0
$ gist edit xyzzy
1615993986.642 ERROR[gist] handle_gist_edit() takes 2 positional arguments but 4 were given
```

**Comment by jdowner** [comment]
Agh! Of course it was working when I tried it before, but I can confirm that this is occurring now. I will fix this today. Sorry about that!

**Comment by jdowner** [comment]
@nealmcb thanks for your patience! Version 0.10.1 has been released and (touch wood) fixes this problem :)

**Comment by nealmcb** [comment]
Confirmed - works well. This is one of the best features of this code!  Many thanks.
